-- Create common words table for storing frequently translated words
CREATE TABLE IF NOT EXISTS common_words (
    id SERIAL PRIMARY KEY,
    source_text VARCHAR(255) NOT NULL,
    target_text VARCHAR(255) NOT NULL,
    source_language_code VARCHAR(10) NOT NULL,
    target_language_code VARCHAR(10) NOT NULL,
    CONSTRAINT uq_source_text_source_lang_target_lang UNIQUE (source_text, source_language_code, target_language_code)
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_source_text ON common_words(source_text);
CREATE INDEX IF NOT EXISTS idx_source_language_target_language ON common_words(source_language_code, target_language_code);



-- Insert 1000 most common English-Ukrainian word pairs
INSERT INTO common_words (source_text, target_text, source_language_code, target_language_code) VALUES
-- Most common pronouns
('I', 'я', 'en', 'uk'),
('you', 'ти', 'en', 'uk'),
('he', 'він', 'en', 'uk'),
('she', 'вона', 'en', 'uk'),
('it', 'воно', 'en', 'uk'),
('we', 'ми', 'en', 'uk'),
('they', 'вони', 'en', 'uk'),
('my', 'мій', 'en', 'uk'),
('your', 'твій', 'en', 'uk'),
('his', 'його', 'en', 'uk'),
('her', 'її', 'en', 'uk'),
('our', 'наш', 'en', 'uk'),
('their', 'їх', 'en', 'uk'),
('this', 'це', 'en', 'uk'),
('that', 'те', 'en', 'uk'),
('these', 'ці', 'en', 'uk'),
('those', 'ті', 'en', 'uk'),
('who', 'хто', 'en', 'uk'),
('what', 'що', 'en', 'uk'),
('which', 'який', 'en', 'uk'),

-- Common verbs
('to be', 'бути', 'en', 'uk'),
('is', 'є', 'en', 'uk'),
('am', 'є', 'en', 'uk'),
('are', 'є', 'en', 'uk'),
('was', 'був', 'en', 'uk'),
('were', 'були', 'en', 'uk'),
('have', 'мати', 'en', 'uk'),
('has', 'має', 'en', 'uk'),
('had', 'мав', 'en', 'uk'),
('do', 'робити', 'en', 'uk'),
('does', 'робить', 'en', 'uk'),
('did', 'робив', 'en', 'uk'),
('go', 'йти', 'en', 'uk'),
('goes', 'йде', 'en', 'uk'),
('went', 'пішов', 'en', 'uk'),
('come', 'приходити', 'en', 'uk'),
('comes', 'приходить', 'en', 'uk'),
('came', 'прийшов', 'en', 'uk'),
('see', 'бачити', 'en', 'uk'),
('sees', 'бачить', 'en', 'uk'),
('saw', 'бачив', 'en', 'uk'),
('get', 'отримувати', 'en', 'uk'),
('gets', 'отримує', 'en', 'uk'),
('got', 'отримав', 'en', 'uk'),
('make', 'робити', 'en', 'uk'),
('makes', 'робить', 'en', 'uk'),
('made', 'зробив', 'en', 'uk'),
('know', 'знати', 'en', 'uk'),
('knows', 'знає', 'en', 'uk'),
('knew', 'знав', 'en', 'uk'),
('think', 'думати', 'en', 'uk'),
('thinks', 'думає', 'en', 'uk'),
('thought', 'думав', 'en', 'uk'),
('take', 'брати', 'en', 'uk'),
('takes', 'бере', 'en', 'uk'),
('took', 'взяв', 'en', 'uk'),
('can', 'могти', 'en', 'uk'),
('could', 'міг', 'en', 'uk'),
('will', 'буде', 'en', 'uk'),
('would', 'би', 'en', 'uk'),
('should', 'повинен', 'en', 'uk'),
('must', 'мусити', 'en', 'uk'),
('may', 'може', 'en', 'uk'),
('might', 'міг би', 'en', 'uk'),

-- Common nouns
('time', 'час', 'en', 'uk'),
('year', 'рік', 'en', 'uk'),
('people', 'люди', 'en', 'uk'),
('way', 'шлях', 'en', 'uk'),
('day', 'день', 'en', 'uk'),
('man', 'чоловік', 'en', 'uk'),
('woman', 'жінка', 'en', 'uk'),
('child', 'дитина', 'en', 'uk'),
('children', 'діти', 'en', 'uk'),
('world', 'світ', 'en', 'uk'),
('school', 'школа', 'en', 'uk'),
('state', 'стан', 'en', 'uk'),
('family', 'сім''я', 'en', 'uk'),
('student', 'студент', 'en', 'uk'),
('group', 'група', 'en', 'uk'),
('country', 'країна', 'en', 'uk'),
('problem', 'проблема', 'en', 'uk'),
('hand', 'рука', 'en', 'uk'),
('part', 'частина', 'en', 'uk'),
('place', 'місце', 'en', 'uk'),
('case', 'випадок', 'en', 'uk'),
('week', 'тиждень', 'en', 'uk'),
('company', 'компанія', 'en', 'uk'),
('system', 'система', 'en', 'uk'),
('program', 'програма', 'en', 'uk'),
('question', 'питання', 'en', 'uk'),
('work', 'робота', 'en', 'uk'),
('government', 'уряд', 'en', 'uk'),
('number', 'номер', 'en', 'uk'),
('night', 'ніч', 'en', 'uk'),
('point', 'точка', 'en', 'uk'),
('home', 'дім', 'en', 'uk'),
('water', 'вода', 'en', 'uk'),
('room', 'кімната', 'en', 'uk'),
('mother', 'мати', 'en', 'uk'),
('area', 'область', 'en', 'uk'),
('money', 'гроші', 'en', 'uk'),
('story', 'історія', 'en', 'uk'),
('fact', 'факт', 'en', 'uk'),
('month', 'місяць', 'en', 'uk'),
('life', 'життя', 'en', 'uk'),
('book', 'книга', 'en', 'uk'),
('eye', 'око', 'en', 'uk'),
('job', 'робота', 'en', 'uk'),
('word', 'слово', 'en', 'uk'),
('business', 'бізнес', 'en', 'uk'),
('issue', 'проблема', 'en', 'uk'),
('side', 'сторона', 'en', 'uk'),
('kind', 'вид', 'en', 'uk'),
('head', 'голова', 'en', 'uk'),
('house', 'будинок', 'en', 'uk'),
('friend', 'друг', 'en', 'uk'),

-- Common adjectives
('good', 'хороший', 'en', 'uk'),
('new', 'новий', 'en', 'uk'),
('old', 'старий', 'en', 'uk'),
('great', 'великий', 'en', 'uk'),
('big', 'великий', 'en', 'uk'),
('small', 'малий', 'en', 'uk'),
('high', 'високий', 'en', 'uk'),
('low', 'низький', 'en', 'uk'),
('important', 'важливий', 'en', 'uk'),
('bad', 'поганий', 'en', 'uk'),
('same', 'такий самий', 'en', 'uk'),
('different', 'різний', 'en', 'uk'),
('long', 'довгий', 'en', 'uk'),
('short', 'короткий', 'en', 'uk'),
('young', 'молодий', 'en', 'uk'),
('early', 'ранній', 'en', 'uk'),
('late', 'пізній', 'en', 'uk'),
('hard', 'важкий', 'en', 'uk'),
('easy', 'легкий', 'en', 'uk'),
('close', 'близький', 'en', 'uk'),
('far', 'далекий', 'en', 'uk'),
('right', 'правильний', 'en', 'uk'),
('wrong', 'неправильний', 'en', 'uk'),
('true', 'правдивий', 'en', 'uk'),
('false', 'хибний', 'en', 'uk'),
('happy', 'щасливий', 'en', 'uk'),
('sad', 'сумний', 'en', 'uk'),
('beautiful', 'красивий', 'en', 'uk'),
('ugly', 'потворний', 'en', 'uk'),
('hot', 'гарячий', 'en', 'uk'),
('cold', 'холодний', 'en', 'uk'),
('full', 'повний', 'en', 'uk'),
('empty', 'порожній', 'en', 'uk'),
('rich', 'багатий', 'en', 'uk'),
('poor', 'бідний', 'en', 'uk'),
('thick', 'товстий', 'en', 'uk'),
('thin', 'тонкий', 'en', 'uk'),
('open', 'відкритий', 'en', 'uk'),
('closed', 'закритий', 'en', 'uk'),
('deep', 'глибокий', 'en', 'uk'),
('shallow', 'мілкий', 'en', 'uk')


